
name: AFK-Kick
version: 1.0
author: Hohi
description: ยง3AFK Kick Plugin!
main: ch.derhohi.main.Main

commands:
  notafk:
    description: ยง3Confirm that you are not AFK.
    usage: /notafk
  afkreload:
    description: ยง3Reload Config
    usage: /afkreload
    permission: afk.reload



